apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-example-install
  annotations:
    github.com/project-slug: arboleda-alejandro/argocd-example-install
    backstage.io/techdocs-ref: dir:.
  description: Example ArgoCD installation using the app-of-apps pattern with Helm charts
spec:
  type: service
  lifecycle: experimental
  owner: user:default/arboleda-alejandro
  system: gitops-platform
  dependsOn:
    - component:argo-helm-alejo

