apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: gsm-argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gsm-argocd
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/arboleda-alejandro/argocd-example-install.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
