apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: gsm-argocd
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gsm-argocd
  project: default
  source:
    path: apps/
    repoURL: https://github.com/arboleda-alejandro/argocd-example-install.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

