argo-cd:
  installCRDs: false
  global:
    image:
      tag: v2.1.1
  dex:
    enabled: false
  server:
    namespace: argocd
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
