argo-cd:
  installCRDs: false
  fullnameOverride: "argocd"
  global:
    securityContext:
      fsGroup: 999
    image:
      tag: v2.1.1
  dex:
    enabled: false
  server:
    affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-server
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/part-of: argocd
              topologyKey: kubernetes.io/hostname
            weight: 5      
    service:
      type: LoadBalancer
      servicePortHttpName: http
      servicePortHttp: 80
      servicePortHttpsName: https
      servicePortHttps: 443
      namedTargetPort: false
    metrics:
      enabled: true
      namedTargetPort: false
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
