argo-scheduling: &argo-scheduling
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: team
            operator: In
            values:
            - fep
  tolerations:
    - key: "team"
      value: "fep"
      operator: "Equal"
      effect: "NoSchedule"
argo-cd:
  installCRDs: false
  fullnameOverride: argocd
  global:
    securityContext:
      fsGroup: 999
    image:
      tag: v2.2.2
  dex:
    enabled: false
  dex:
    <<: *argo-scheduling
  redis:
    <<: *argo-scheduling
  repoServer:
    <<: *argo-scheduling
    replicas: 2
  controller:
    <<: *argo-scheduling
  server:
    <<: *argo-scheduling
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 54Mi
    extraArgs:
      - --insecure
    replicas: 2
    env:
    - name: ARGOCD_CONTROLLER_REPLICAS
      value: "2"
    service:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: argocd-server
        app.kubernetes.io/part-of: argocd
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://artifacthub.github.io/helm-charts/
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm  


pdb:
  deployments:
  - name: argocd-server
    namespace: gsm-argocd
    minAvailable: 1
    instanceName: argo-cd
  - name: argocd-repo-server
    namespace: gsm-argocd
    minAvailable: 1
    instanceName: argo-cd
