argo-scheduling: &argo-scheduling
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: team
            operator: In
            values:
            - fep
  tolerations:
    - key: "team"
      value: "fep"
      operator: "Equal"
      effect: "NoSchedule"
argo-cd:
  installCRDs: false
  fullnameOverride: argocd
  global:
    securityContext:
      fsGroup: 999
    image:
      tag: v2.1.1
  dex:
    enabled: false
  dex:
    <<: *argo-scheduling
  redis:
    <<: *argo-scheduling
  repoServer:
    <<: *argo-scheduling
  controller:
    <<: *argo-scheduling
  server:
    <<: *argo-scheduling
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 54Mi
    extraArgs:
      - --insecure
    service:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: argocd-server
        app.kubernetes.io/part-of: argocd
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://artifacthub.io/ 
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm  
